create database customer_behavior;
use customer_behavior;

select * from customer limit 10;

-- Q1. What is the Total Revenue Generated by male vs female customers
SELECT gender, sum(purchase_amount) as "Total Revenue" 
from customer 
group by gender;

-- Q2. Which Customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount 
from customer
where discount_applied = "Yes" and purchase_amount>= (select avg(purchase_amount) from customer);

-- Q3. Which are the Top 10 Prodcts with the highest average review rating
select item_purchased, Round(avg(review_rating),2) as review
from customer
group by item_purchased
order by avg(review_rating) desc limit 10;

-- Q4. Compare the Average Purchase Amount between Standard and Express Shipping
select shipping_type, round(avg(purchase_amount),2) as Average 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, count(customer_id) as Total_Customer,
Round(avg(purchase_amount),2) as Average_Spent,
Round(sum(purchase_amount),2) as Total_Revenue
from customer
group by subscription_status
Order by total_revenue,average_spent desc;

-- Q6. Which 5 Products have the highest percentage of perchase with discount applied?
select item_purchased, 
round(sum(
CASE WHEN discount_applied='Yes' Then 1 Else 0 END) / count(*)*100,2) as Discount_Rate 
from customer
group by item_purchased
order by discount_rate desc 
limit 5;

-- Q7. Segment Customer Into New, Returning, and Loyal Based on their total no.of Previous Purchases, and show the count of each segment
with customer_type as (
select previous_purchases,
CASE
	WHEN previous_purchases= 1 THEN 'New' 
    WHEN previous_purchases between 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
from customer)
select customer_segment, count(*) as "No.of Customer"
from customer_type
group by customer_segment;
select * from customer;

-- Q8. What are the Top 3 Most Purchased products within each category?
with item_count as (
select category,item_purchased,
count(customer_id) as Total_order,
ROW_NUMBER() OVER(Partition by category order by count(customer_id) DESC) as Item_Rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_order
from item_count
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous perchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the Revenue contribute of each age group
select age_group, sum(purchase_amount) as Revenue
from customer
group by age_group
order by revenue desc;